<?php

function generateColors() {
	$colors = array();

	$colors[] = array( 0 => 226, 1 => 207, 2 => 86);
	$colors[] = array( 0 => 86, 1 => 104, 2 => 226);

	$colors[] = array( 0 => 174, 1 => 226, 2 => 86);
	$colors[] = array( 0 => 138, 1 => 86, 2 => 226);
	
	$colors[] = array( 0 => 104, 1 => 226, 2 => 86);
	$colors[] = array( 0 => 207, 1 => 86, 2 => 226);
	
	$colors[] = array( 0 => 86, 1 => 226, 2 => 137);
	$colors[] = array( 0 => 226, 1 => 86, 2 => 174);
	
	$colors[] = array( 0 => 86, 1 => 226, 2 => 207);
	$colors[] = array( 0 => 226, 1 => 86, 2 => 104);
	
	$colors[] = array( 0 => 86, 1 => 174, 2 => 226);
	$colors[] = array( 0 => 226, 1 => 137, 2 => 86);

	$colors[] = array( 0 => 145, 1 => 0, 2 => 0 );
	$colors[] = array( 0 => 0, 1 => 87, 2 => 87 );
	$colors[] = array( 0 => 145, 1 => 66, 2 => 0 );
	$colors[] = array( 0 => 0, 1 => 166, 2 => 0 );
	$colors[] = array( 0 => 227, 1 => 72, 2 =>  72);

	$colors[] = array( 0 => 43, 1 => 136, 2 => 136 );
	$colors[] = array( 0 => 227, 1 => 142, 2 => 72 );
	$colors[] = array( 0 => 58, 1 => 181, 2 => 58 );

	$colors[] = array( 0 => 169, 1 => 213, 2 => 238 );
	$colors[] = array( 0 => 1, 1 => 53, 2 => 102 );
	$colors[] = array( 0 => 238, 1 => 169, 2 => 213 );
	$colors[] = array( 0 => 213, 1 => 238, 2 => 169 );
	$colors[] = array( 0 => 102, 1 => 1, 2 =>  3);

	$colors[] = array( 0 => 238, 1 => 169, 2 => 179 );
	$colors[] = array( 0 => 238, 1 => 194, 2 => 169 );
	$colors[] = array( 0 => 169, 1 => 238, 2 => 194 );
	$colors[] = array( 0 => 238, 1 => 229, 2 => 169 );
	$colors[] = array( 0 => 238, 1 => 211, 2 => 169 );

	$colors[] = array( 0 => 169, 1 => 182, 2 => 238 );
	$colors[] = array( 0 => 236, 1 => 93, 2 => 93 );
	$colors[] = array( 0 => 236, 1 => 211, 2 => 93 );
	$colors[] = array( 0 => 104, 1 => 236, 2 => 93 );
	$colors[] = array( 0 => 93, 1 => 236, 2 => 231 );

	$colors[] = array( 0 => 110, 1 => 93, 2 => 236 );
	$colors[] = array( 0 => 23, 1 => 106, 2 => 121 );
	$colors[] = array( 0 => 101, 1 => 23, 2 => 121 );
	$colors[] = array( 0 => 121, 1 => 23, 2 => 81 );
	$colors[] = array( 0 => 252, 1 => 131, 2 => 2 );

	return $colors;
}

?>