<?php

function generateColors() {
	$colors = array();

	$colors[] = array( 0 => 169, 1 => 213, 2 => 238 );
	$colors[] = array( 0 => 1, 1 => 53, 2 => 102 );
	$colors[] = array( 0 => 238, 1 => 169, 2 => 213 );
	$colors[] = array( 0 => 213, 1 => 238, 2 => 169 );
	$colors[] = array( 0 => 238, 1 => 229, 2 => 169 );

	$colors[] = array( 0 => 238, 1 => 169, 2 => 179 );
	$colors[] = array( 0 => 238, 1 => 194, 2 => 169 );
	$colors[] = array( 0 => 169, 1 => 238, 2 => 194 );
	$colors[] = array( 0 => 102, 1 => 1, 2 =>  3);
	$colors[] = array( 0 => 238, 1 => 211, 2 => 169 );

	$colors[] = array( 0 => 169, 1 => 182, 2 => 238 );
	$colors[] = array( 0 => 236, 1 => 93, 2 => 93 );
	$colors[] = array( 0 => 236, 1 => 211, 2 => 93 );
	$colors[] = array( 0 => 104, 1 => 236, 2 => 93 );
	$colors[] = array( 0 => 93, 1 => 236, 2 => 231 );

	$colors[] = array( 0 => 110, 1 => 93, 2 => 236 );
	$colors[] = array( 0 => 23, 1 => 106, 2 => 121 );
	$colors[] = array( 0 => 101, 1 => 23, 2 => 121 );
	$colors[] = array( 0 => 121, 1 => 23, 2 => 81 );
	$colors[] = array( 0 => 252, 1 => 131, 2 => 2 );

	return $colors;
}

?>